[package]
name = "tvcg-journal"
version = "0.0.1"
compiler = "0.10.0"
entrypoint = "lib.typ"
repository = "https://github.com/domoritz/tvcg-journal-typst"
authors = ["Matěj Lang <https://www.linkedin.com/in/matej-lang/>", "Dominik Moritz <https://www.domoritz.de>"]
license = "MIT-0"
description = "A template for TVCG journal papers."
keywords = ["Institute of Electrical and Electronics Engineers", "IEEE", "Transactions on Visualization and Computer Graphics", "TVCG", "Computer Science", "Visualization"]
categories = ["paper"]
disciplines = ["computer-science"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
